version: '3'

networks:
  bqnet:
    external: true

services:

  roudi:
    image: roudi:2.0.2
    container_name: roudi
    build:
      context: ./roudi
      dockerfile: ../../bqipc/docker/Dockerfile
    command: iox-roudi
    volumes:
      - /dev:/dev
      - /tmp:/tmp
    healthcheck:
      test: ps -ef|grep -i iox

  mysql:
    image: mysql:5.7.44
    container_name: bqdb
    ports:
      - 3306:3306
    volumes:
      - $ROOT_DIR_OF_SOLUTION/bqdb/sql:/docker-entrypoint-initdb.d
      - $ROOT_DIR_OF_INSTALLATION/mysql/data:/var/lib/mysql
      - $ROOT_DIR_OF_INSTALLATION/mysql/conf.d:/etc/mysql/conf.d
      - $ROOT_DIR_OF_INSTALLATION/mysql/logs:/logs
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWD}"
      MYSQL_DATABASE: BetterQuant
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks: 
      - bqnet

  bqmd-sim-multi-market:
    image: bqmd-sim:${TAG}
    container_name: bqmd-sim-multi-market
    build:
      context: ./bqmd-sim
      dockerfile: ../../bqmd/bqmd-sim/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-sim', '--conf=config/bqmd-sim/bqmd-sim.yaml']

  bqmd-binance-spot:
    image: bqmd-binance:${TAG}
    container_name: bqmd-binance-spot
    build:
      context: ./bqmd-binance
      dockerfile: ../../bqmd/bqmd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-binance', '--conf=config/bqmd-binance/spot/bqmd-binance.yaml']

  bqmd-binance-perp:
    image: bqmd-binance:${TAG}
    container_name: bqmd-binance-perp
    build:
      context: ./bqmd-binance
      dockerfile: ../../bqmd/bqmd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-binance', '--conf=config/bqmd-binance/perp/bqmd-binance.yaml']

  bqmd-binance-cperp:
    image: bqmd-binance:${TAG}
    container_name: bqmd-binance-cperp
    build:
      context: ./bqmd-binance
      dockerfile: ../../bqmd/bqmd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-binance', '--conf=config/bqmd-binance/cperp/bqmd-binance.yaml']

  bqmd-binance-futures:
    image: bqmd-binance:${TAG}
    container_name: bqmd-binance-futures
    build:
      context: ./bqmd-binance
      dockerfile: ../../bqmd/bqmd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-binance', '--conf=config/bqmd-binance/futures/bqmd-binance.yaml']

  bqmd-binance-cfutures:
    image: bqmd-binance:${TAG}
    container_name: bqmd-binance-cfutures
    build:
      context: ./bqmd-binance
      dockerfile: ../../bqmd/bqmd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqmd-binance', '--conf=config/bqmd-binance/cfutures/bqmd-binance.yaml']

  bqtd-binance:
    image: bqtd-binance:${TAG}
    container_name: bqtd-binance
    build:
      context: ./bqtd-binance
      dockerfile: ../../bqtd/bqtd-binance/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy

  bqtd-srv:
    image: bqtd-srv:${TAG}
    container_name: bqtd-srv
    build:
      context: ./bqtd-srv
      dockerfile: ../../bqtd/bqtd-srv/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - $ROOT_DIR_OF_INSTALLATION/betterquant/plugin:/usr/bin/plugin
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy

  bqriskmgr:
    image: bqriskmgr:${TAG}
    container_name: bqriskmgr
    build:
      context: ./bqriskmgr
      dockerfile: ../../bqriskmgr/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy

  bqweb-srv:
    image: bqweb-srv:${TAG}
    container_name: bqweb-srv
    ports:
      - 80:80
      - 443:443
    build:
      context: ./bqweb-srv
      dockerfile: ../../bqweb-srv/docker/Dockerfile
    volumes:
      - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
      - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
      - /dev:/dev
      - /tmp:/tmp
    restart: always
    stop_signal: SIGINT
    networks:
      - bqnet
    depends_on: 
      roudi:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ['bqweb-srv', '--conf=config/bqweb-srv/bqweb-srv.yaml']
